// sources/angular-app/src/app/bio/bio.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-bio',
  templateUrl: './bio.component.html',
  styleUrls: ['./bio.component.scss']
})
export class BioComponent implements OnInit {
  @Input() bio;
  public name;
  public profilePic;
  public bioText;
  public showLinkButton;
  public linkButtonText;
  public linkButtonUrl;
  public facebookLink;
  public twitterLink;
  public instagramLink;
  public youTubeLink;

  constructor() {
  }

  ngOnInit(): void {
    // TODO: can be used directly from bio. ???
    this.name = this.bio.name_s;
    this.profilePic = this.bio.profilePic_s;
    this.linkButtonUrl = this.bio.linkButtonUrl_s;
    this.showLinkButton = this.bio.showLinkButton_b;
    this.linkButtonText = this.bio.linkButtonText_s;
    this.bioText = this.bio.bio_t;
    this.facebookLink = this.bio.facebookLink_s;
    this.twitterLink = this.bio.twitterLink_s;
    this.instagramLink = this.bio.instagramLink_s;
    this.youTubeLink = this.bio.youTubeLink_s;
  }

}

<div class="bio text-center">
  <img class="img-fluid" src="{{profilePic}}">
  <div class="bio-body">
    <h2>{{name}}</h2>

    <p *ngIf="showLinkButton">
      <a class="btn btn-primary btn-sm rounded" href="{{linkButtonUrl}}">{{linkButtonText}}</a>
    </p>
    <p>{{bioText}}</p>
    <p class="social">
      <a *ngIf="facebookLink" class="p-2" href="{{facebookLink}}">
        <span class="fa fa-facebook"></span>
      </a>
      <a *ngIf="twitterLink" class="p-2" href="{{twitterLink}}">
        <span class="fa fa-twitter"></span>
      </a>
      <a *ngIf="instagramLink" class="p-2" href="{{instagramLink}}">
        <span class="fa fa-instagram"></span>
      </a>
      <a *ngIf="youTubeLink" class="p-2" href="{{youTubeLink}}">
        <span class="fa fa-youtube-play"></span>
      </a>
    </p>
  </div>
</div>

// sources/react-app/src/components/Bio.js
import React from 'react';

export default function (props) {
  const {
    ice,
    model: {
      // craftercms: {
      //   id,
      //   contentTypeId,
      //   label,
      //   path,
      // },
      bio_t,
      name_s,
      profilePic_s,
      linkButtonText_s,
      linkButtonUrl_s,
      showLinkButton_b
    }
  } = props;
  return (
    <>
      <div className="bio text-center" {...ice}>
        <img src={profilePic_s} alt="" className="img-fluid"/>
        <div className="bio-body">
          <h2>{name_s}</h2>
          <p>{bio_t}</p>
          {
            showLinkButton_b &&
            <p>
              <a href={linkButtonUrl_s} className="btn btn-primary btn-sm rounded">
                {linkButtonText_s}
              </a>
            </p>
          }
          <p className="social">
            <a href="/" className="p-2"><span className="fa fa-facebook"/></a>
            <a href="/" className="p-2"><span className="fa fa-twitter"/></a>
            <a href="/" className="p-2"><span className="fa fa-instagram"/></a>
            <a href="/" className="p-2"><span className="fa fa-youtube-play"/></a>
          </p>
        </div>
      </div>
    </>
  );
}
