// sources/react-app/src/pages/Search.jsx
/*
 * Copyright (C) 2007-2022 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import React, { Suspense, useState } from 'react';
import BaseLayout from '../shared/BaseLayout';
import { FormattedMessage } from 'react-intl';
import SidebarSearch from '../shared/SidebarSearch';
import RecentPostsAside from '../shared/RecentPostsAside';
import { SidebarCategories, SidebarTags } from '../shared/SidebarTaxonomies';
import { useSearchQuery, useUrlSearchQueryFetchResource } from '../shared/hooks';
import CircularProgressSpinner from '../shared/CircularProgressSpinner';
import PostCard, { LANDSCAPE } from '../shared/PostCard';
import { useHistory } from 'react-router-dom'
import { SidebarBiosWithICE } from '../shared/SidebarBios';
import Paginate from '../shared/Paginate';

function SearchResults({ resource, paginationData, onPageChange }) {
  const { hits, total } = resource.read();

  const totalResults = typeof total === 'object' ? total.value : total;
  const pageCount = Math.ceil(totalResults/paginationData.itemsPerPage);
  return (
    <>
      <p>{totalResults} result{totalResults === 0 || totalResults > 1 ? 's' : ''} found.</p>
      {
        hits.map((post) =>
            <div className="col-md-6"><PostCard key={post.craftercms.id} model={post} render={LANDSCAPE} /></div>
        )
      }

      {
        pageCount > 1 &&
        <div className="col-md-12 text-center mt-5">
          <Paginate
            pageCount={pageCount}
            onPageChange={(index) => onPageChange(index * paginationData.itemsPerPage)}
          />
        </div>
      }
    </>
  );
}

function Search(props) {
  const {
    model,
    meta: {
      levelDescriptor
    }
  } = props;
  const [paginationData, setPaginationData] = useState({
    itemsPerPage: 10,
    currentPage: 0
  });
  let resource = useUrlSearchQueryFetchResource(paginationData.itemsPerPage);

  const history = useHistory();
  const [query] = useSearchQuery();

  const onPageChange = (page) => {
    setPaginationData({ ...paginationData, currentPage: page})
    history.push({
      pathname: '/search',
      search: `?q=${query}&p=${page}`
    });
  }

  return (
    <BaseLayout model={levelDescriptor}>
      <section className="site-section pt-5 py-sm">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <h2 className="mb-4">
                <FormattedMessage
                  id="common.latestPostSectionTitle"
                  defaultMessage="Search Results"
                />
              </h2>
            </div>
          </div>
          <div className="row blog-entries">
            <div className="col-md-12 col-lg-8 main-content">
              <div className="row">
                <Suspense fallback={<CircularProgressSpinner screenHeight={false} />}>
                  <SearchResults
                    resource={resource}
                    paginationData={paginationData}
                    onPageChange={onPageChange}
                  />
                </Suspense>
              </div>
            </div>
            <div className="col-md-12 col-lg-4 sidebar">

              <SidebarSearch />

              <SidebarBiosWithICE model={model} fieldId="bios_o" />

              <RecentPostsAside />

              <SidebarCategories />

              <SidebarTags />

            </div>
          </div>
        </div>
      </section>
    </BaseLayout>
  );
}

export default Search;

// sources/angular-app/src/app/search/search.component.ts
/*
 * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import { Component, Input, OnInit } from '@angular/core';
import { ContentService } from '../content.service';
import { defaultData } from '../pagination/pagination.component';
import { map } from 'rxjs/operators';
import { parseDescriptor, preParseSearchResults } from '@craftercms/content';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss']
})
export class SearchComponent implements OnInit {
  @Input() state;
  public results = [];
  public paginationData = defaultData;
  public keyword = '';
  public bios_o;
  public totalResults = 0;

  constructor(private contentService: ContentService, private actRoute: ActivatedRoute){}

  getResults(): void {
    this.contentService.searchPosts(
      this.keyword,
      this.paginationData.itemsPerPage,
      (this.paginationData.currentPage * this.paginationData.itemsPerPage)
    )
      .pipe(    // TODO: move this to service, error in service
        map(({ hits, total, ...rest }) => {
          const parsedHits = hits.map(({ _source }) => parseDescriptor(
            preParseSearchResults(_source)
          ));
          return { ...rest, hits: parsedHits, total: total.value??total };
        })
      )
      .subscribe(response => {
        this.paginationData.pageCount = Math.ceil(response.total / this.paginationData.itemsPerPage);
        this.results = response.hits;
        this.totalResults = response.total
      });
  }

  onPageChange(page: number) {
    this.paginationData.currentPage = page;
    this.getResults();
  }

  ngOnInit(): void {
    this.bios_o = this.state.model.bios_o;
    this.paginationData.itemsPerPage = this.state.meta.posts.limit;
    this.actRoute.queryParams.subscribe(parameters => {
      this.keyword = parameters.q;
      this.getResults();
    });
  }
}

<section class="site-section pt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="mb-4">
          Search Results
        </h2>
      </div>
    </div>
    <div class="row blog-entries">
      <div class="col-md-12 col-lg-8 main-content">
        <div class="row mb-5 mt-5">
          <div class="col-md-12">
            <p>{{totalResults}} result{{totalResults === 0 || totalResults > 1 ? 's' : ''}} found.</p>
            <app-post-card
              *ngFor="let result of results;" [format]="'landscape'" [model]="result"
            ></app-post-card>
          </div>
        </div>
        <div *ngIf="paginationData.pageCount > 1" class="row">
          <div class="col-md-12 text-center">
            <nav aria-label="Page navigation" class="text-center">
              <app-pagination
                [currentPage]="paginationData.currentPage"
                [itemsPerPage]="paginationData.itemsPerPage"
                [pageCount]="paginationData.pageCount"
                [onPageChange]="onPageChange.bind(this)"
              ></app-pagination>
            </nav>
          </div>
        </div>
      </div>
      <div class="col-md-12 col-lg-4 sidebar">

        <app-sidebar-search></app-sidebar-search>

        <app-sidebar-bios [bios]="bios_o"></app-sidebar-bios>

        <app-recent-posts-aside></app-recent-posts-aside>

        <app-sidebar-categories></app-sidebar-categories>

        <app-sidebar-tags></app-sidebar-tags>

      </div>
    </div>
  </div>
</section>
