// sources/react-app/src/shared/CategoryCard.jsx

/*
 * Copyright (C) 2007-2022 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import React from 'react';
import { Link } from 'react-router-dom';
import { Field } from '@craftercms/experience-builder/react';

function CategoryCard(props) {
  const {
    model,
    category,
    isTag
  } = props;

  const link = isTag ? 'tag' : 'category'

  return(
    <Field component={Link} model={model} to={`/${link}/${category.key}`} className="blog-entry category-card">
      {
        category.image_s &&
        <img className="background" src={category.image_s} alt={category.value}/>
      }
      <h2 className="title">{category.value}</h2>
    </Field>
  )
}

export default CategoryCard;

// sources/angular-app/src/app/category-card/category-card.component.ts
/*
 * Copyright (C) 2007-2022 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-category-card',
  templateUrl: './category-card.component.html',
  styleUrls: ['./category-card.component.scss']
})
export class CategoryCard implements OnInit {
  @Input() category;
  @Input() isTag;
  public link;

  constructor() {}

  ngOnInit() {
    this.link = `/${ this.isTag ? 'tag' : 'category' }/${this.category.key}`;
  }
}

<!--
  ~ Copyright (C) 2007-2022 Crafter Software Corporation. All Rights Reserved.
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License version 3 as published by
  ~ the Free Software Foundation.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<a routerLink="{{link}}" class="blog-entry category-card">
  <img *ngIf="category.image_s" class="background" src="{{category.image_s}}" alt="{{category.value}}"/>
  <h2 class="title">{{ category.value }}</h2>
</a>
