// sources/angular-app/src/app/contact/contact.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ContentService } from '../content.service';

const initialFormData = {
  name: '',
  phone: '',
  email: '',
  message: ''
};

const initialToastData = {
  display: false,
  type: '',
  text: ''
};

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss']
})
export class ContactComponent implements OnInit {
  @Input() state;
  public posts_o;
  public formData = { ...initialFormData };
  public toastData = { ...initialToastData };

  constructor(private contentService: ContentService) {
  }

  showToast(text: string, type: string) {
    this.toastData = {
      display: true,
      text,
      type
    };
    setTimeout(() => {
      this.toastData = { ...initialToastData };
    }, 3000);
  }

  handleSubmit() {
    this.contentService.submitContactData(this.formData)
      .subscribe(response => {
        if (response.success) {
          this.formData = { ...initialFormData };
          this.showToast('Message successfully sent!', 'success');
        } else {
          this.showToast('There was an error sending the message', 'danger');
        }
      })

  }

  ngOnInit(): void {
    this.posts_o = this.state.posts;
  }

}

<section class="site-section">
  <div class="container">
    <div class="row mb-4">
      <div class="col-md-6">
        <h1>Contact Me</h1>
      </div>
    </div>
    <div class="row blog-entries">
      <div class="col-md-12 col-lg-8 main-content">

        <form (ngSubmit)="handleSubmit()">
          <div class="row">
            <div class="col-md-12 form-group">
              <label htmlFor="name">Name</label>
              <input
                class="form-control "
                id="name"
                name="name"
                type="text"
                [(ngModel)]="formData.name"/>
            </div>
            <div class="col-md-12 form-group">
              <label htmlFor="phone">Phone</label>
              <input
                class="form-control "
                id="phone"
                name="phone"
                type="text"
                [(ngModel)]="formData.phone"
              />
            </div>
            <div class="col-md-12 form-group">
              <label htmlFor="email">Email</label>
              <input
                class="form-control "
                id="email"
                name="email"
                type="email"
                [(ngModel)]="formData.email"
              />
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 form-group">
              <label htmlFor="message">Write Message</label>
              <textarea
                class="form-control "
                cols="30"
                id="message"
                name="message"
                rows="8"
                [(ngModel)]="formData.message"
              ></textarea>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 form-group">
              <input class="btn btn-primary" type="submit" value="Send Message" />
            </div>
          </div>
        </form>

      </div>

      <div class="col-md-12 col-lg-4 sidebar">
        <div class="sidebar-box search-form-wrap">
          <form action="#" class="search-form">
            <div class="form-group">
              <span class="icon fa fa-search"></span>
              <input
                class="form-control" id="s" placeholder="Type a keyword and hit enter" type="text"
              />
            </div>
          </form>
        </div>

        <app-recent-posts-aside></app-recent-posts-aside>

        <app-sidebar-categories></app-sidebar-categories>

        <app-sidebar-tags></app-sidebar-tags>

      </div>

    </div>
  </div>

  <app-toast
    [display]="toastData.display"
    [type]="toastData.type"
    [text]="toastData.text"
  ></app-toast>
</section>

// sources/react-app/src/pages/Contact.js
/*
 * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import React, { useState } from 'react';
import BaseLayout from '../shared/BaseLayout';
import RecentPostsAside from '../shared/RecentPostsAside';
import { SidebarCategories, SidebarTags } from '../shared/SidebarTaxonomies';
import { ajax } from 'rxjs/ajax';
import { catchError } from 'rxjs/operators';
import Toast from '../components/Toast';
import { defineMessages, useIntl } from 'react-intl';
import { RenderField } from '@craftercms/studio-guest';

const translations = defineMessages({
  contactSuccess: {
    id: 'contact.contactSuccess',
    defaultMessage: 'Message successfully sent!'
  }
});

const initialFormData = {
  name: '',
  phone: '',
  email: '',
  message: ''
}

const initialToastData = {
  display: false,
  type: '',
  text: ''
}

function Contact(props) {
  const {
    model,
    meta: {
      levelDescriptor
    }
  } = props;

  const { formatMessage } = useIntl();
  const [formData, setFormData] = useState(initialFormData);
  const [toastData, setToastData] = useState(initialToastData);
  const showToast = (text, type) => {
    setToastData({
      display: true,
      text,
      type
    });
    setTimeout(() => {
      setToastData(initialToastData);
    }, 3000);
  }

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value.trim()
    });
  };

  const handleSubmit = function(e) {
    e.preventDefault();

    ajax.post(
      '/api/contactus.json',
      formData,
      {
        'Content-Type': 'application/json'
      }
    ).pipe(
      catchError(error => [error])
    ).subscribe(response => {
      if (response.name === 'AjaxError') {
        showToast('There was an error sending the message', 'danger');
      } else {
        setFormData(initialFormData);
        showToast(formatMessage(translations[response.response.messageKey]), 'success');
      }
    });
  }

  return (
    <BaseLayout model={levelDescriptor}>
      <section className="site-section">
        <div className="container">
          <div className="row mb-4">
            <div className="col-md-6">
              <RenderField component="h1" model={model} fieldId="headline_s" />
              <RenderField component="p" model={model} fieldId="message_t" />
            </div>
          </div>
          <div className="row blog-entries">
            <div className="col-md-12 col-lg-8 main-content">

              <form onSubmit={handleSubmit}>
                <div className="row">
                  <div className="col-md-12 form-group">
                    <label htmlFor="name">Name</label>
                    <input
                      type="text"
                      id="name"
                      name="name"
                      className="form-control"
                      value={formData.name}
                      onChange={handleChange}
                      required
                    />
                  </div>
                  <div className="col-md-12 form-group">
                    <label htmlFor="phone">Phone</label>
                    <input
                      type="text"
                      id="phone"
                      name="phone"
                      className="form-control"
                      value={formData.phone}
                      onChange={handleChange}
                    />
                  </div>
                  <div className="col-md-12 form-group">
                    <label htmlFor="email">Email</label>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      className="form-control"
                      value={formData.email}
                      onChange={handleChange}
                      required
                    />
                  </div>
                </div>
                <div className="row">
                  <div className="col-md-12 form-group">
                    <label htmlFor="message">Write Message</label>
                    <textarea
                      name="message"
                      id="message"
                      className="form-control"
                      cols="30"
                      rows="8"
                      value={formData.message}
                      onChange={handleChange}
                      required
                    />
                  </div>
                </div>
                <div className="row">
                  <div className="col-md-6 form-group">
                    <input type="submit" value="Send Message" className="btn btn-primary"/>
                  </div>
                </div>
              </form>

            </div>

            <div className="col-md-12 col-lg-4 sidebar">
              <div className="sidebar-box search-form-wrap">
                <form action="#" className="search-form">
                  <div className="form-group">
                    <span className="icon fa fa-search"/>
                    <input type="text" className="form-control" id="s" placeholder="Type a keyword and hit enter"/>
                  </div>
                </form>
              </div>

              <RecentPostsAside />

              <SidebarCategories/>

              <SidebarTags/>

            </div>

          </div>
        </div>
      </section>
      <Toast
        display={toastData.display}
        type={toastData.type}
        text={toastData.text}
      />
    </BaseLayout>
  );
}

export default Contact;
