// sources/angular-app/src/app/post-card/post-card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import Utils from '../utils';

export const
  PORTRAIT = 'portrait',
  LANDSCAPE = 'landscape',
  LANDSCAPE_COMPRESSED = 'landscapeCompressed',
  IMAGE_BACKGROUND = 'imageBackground';

@Component({
  selector: 'app-post-card',
  templateUrl: './post-card.component.html',
  styleUrls: ['./post-card.component.scss']
})
export class PostCardComponent implements OnInit {
  @Input() tags = '';
  @Input() model;
  @Input() showBlurb = false;
  @Input() format = PORTRAIT;
  @Input() classes;
  @Input() numOfComments;
  public mainImage_s;
  public blurb_t;
  public headline_s;
  public dateModified;
  public type;
  public authorAvatarUrl;
  public authorName;
  public slug;
  public categories;

  constructor() {
  }

  ngOnInit(): void {
    this.type = this.format;
    this.mainImage_s = this.model.mainImage_s;
    this.headline_s = this.model.headline_s;
    this.dateModified = Utils.formatDate(this.model.craftercms.dateModified);
    this.blurb_t = this.model.blurb_t;
    this.authorAvatarUrl = this.model.authorBio_o[0].profilePic_s;
    this.authorName = this.model.authorBio_o[0].name_s;
    this.slug = Utils.computeSlug(this.model.craftercms.path);
    this.categories = this.model.categories_o;
  }

}

<div [ngSwitch]="type">
  <div
    *ngSwitchCase="'imageBackground'"
    [ngStyle]="{ 'background-image': 'url(' + mainImage_s + ')'}"
    class="a-block d-flex align-items-center {{classes?.root}}"
  >
    <a class="text {{classes?.innerWrapper}}" routerLink="{{slug}}">
      <div class="post-meta">
        <div *ngIf="categories">
          <span *ngFor="let category of categories" class="category">{{category.value_smv}}</span>
          <span> • </span>
        </div>
        <span class="mr-2">{{dateModified}}</span>
        <span *ngIf="numOfComments"> • </span>
        <span *ngIf="numOfComments" class="ml-2">
          <span class="fa fa-comments"></span>{{numOfComments}}
        </span>
      </div>
      <h3>{{headline_s}}</h3>
      <p *ngIf="showBlurb">{{blurb_t}}</p>
    </a>
  </div>
  <a *ngSwitchCase="'portrait'" class="blog-entry {{classes?.root}}" routerLink="{{slug}}">
    <div class="img-container">
      <img src="{{mainImage_s}}">
    </div>
    <div class="blog-content-body">
      <div class="post-meta">
        <span class="author mr-2">
          <img src="{{authorAvatarUrl}}">
          {{authorName}}
        </span>
        <span> • </span>
        <span class="mr-2">{{dateModified}}</span>
        <span *ngIf="numOfComments"> • </span>
        <span *ngIf="numOfComments" class="ml-2">
          <span class="fa fa-comments"></span>{{numOfComments}}
        </span>
      </div>
      <h2>{{headline_s}}</h2>
    </div>
  </a>
  <a *ngSwitchCase="'landscapeCompressed'" class="{{classes?.root}}" routerLink="{{slug}}">
    <img class="mr-4" src="{{mainImage_s}}">
    <div class="text">
      <h4>{{headline_s}}</h4>
      <div class="post-meta">
        <span class="mr-2">{{dateModified}}</span>
      </div>
    </div>
  </a>
  <div *ngSwitchCase="'landscape'" class="post-entry-horizontal">
    <a class="{{classes?.root}}" routerLink="{{slug}}">
      <div [ngStyle]="{ 'background-image': 'url(' + mainImage_s + ')'}" class="image"></div>
      <span class="text">
        <div class="post-meta">
          <span class="author mr-2">
            <img src="{{authorAvatarUrl}}">
            {{authorName}}
          </span>
          <span> • </span>
          <span class="mr-2">{{dateModified}}</span>
          <span *ngIf="numOfComments"> • </span>
          <span *ngIf="numOfComments" class="ml-2">
            <span class="fa fa-comments"></span>{{numOfComments}}
          </span>
        </div>
        <h2>{{headline_s}}</h2>
      </span>
    </a>
  </div>
  <div *ngSwitchDefault>no view</div>
</div>

// sources/react-app/src/shared/PostCard.js
/*
 * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import React from 'react';
import { Link } from 'react-router-dom';
import { useIntl } from 'react-intl';
import { useICE } from '@craftercms/ice/react';
import { useGlobalContext } from './context';

export const
  PORTRAIT = 'portrait',
  LANDSCAPE = 'landscape',
  LANDSCAPE_COMPRESSED = 'landscapeCompressed',
  IMAGE_BACKGROUND = 'imageBackground';

export default function (props) {
  const { formatDate } = useIntl();
  const [{ isAuthoring }] = useGlobalContext();
  const {
    classes,
    parentModelId,
    format = PORTRAIT,
    showBlurb = false,
    numOfComments,
    model,
    model: {
      // pageTitle_s,
      // pageDescription_s,
      // authorBio_o,
      authorBio_o: [{
        name_s: authorName,
        profilePic_s: authorAvatarUrl
      }],
      blurb_t,
      // content_o,
      headline_s,
      mainImage_s,
      mainImageAlt_s = '',
      categories_o,
      craftercms: {
        dateModified
      },
    }
  } = props;
  const slug = model.craftercms.path
    .replace(/(\/site\/components)|(index\.xml)/g, '')
    .replace(/(\/site\/website)|(index\.xml)/g, '')
    .replace(/(\/\/)/g, '/')
    .replace('.xml', '');
  const { props: ice } = useICE({ model, parentModelId, isAuthoring });
  switch (format) {
    case PORTRAIT:
      return (
        <Link to={slug} className={`blog-entry ${classes?.root ?? ''}`} {...ice}>
          <img src={mainImage_s} alt={mainImageAlt_s} />
          <div className="blog-content-body">
            <div className="post-meta">
              <span className="author mr-2">
                <img src={authorAvatarUrl} alt="" /> {authorName}
              </span>
              {' • '}<span className="mr-2">{formatDate(dateModified)}</span>
              {
                numOfComments &&
                <>
                  {' • '}<span className="ml-2"><span className="fa fa-comments" /> {numOfComments}</span>
                </>
              }
            </div>
            <h2>{headline_s}</h2>
          </div>
        </Link>
      );
    case LANDSCAPE:
      return (
        <div className="post-entry-horizontal" {...ice}>
          <Link to={slug} className={classes?.root}>
            <div className="image" style={{ backgroundImage: `url(${mainImage_s})` }} />
            <span className="text">
              <div className="post-meta">
                <span className="author mr-2">
                  <img src={authorAvatarUrl} alt="" /> {authorName}
                </span>
                • <span className="mr-2">{formatDate(dateModified)}</span>
                {
                  numOfComments &&
                  <>
                    • <span className="ml-2"><span className="fa fa-comments" /> ${numOfComments}</span>
                  </>
                }
              </div>
              <h2>{headline_s}</h2>
            </span>
          </Link>
        </div>
      );
    case LANDSCAPE_COMPRESSED:
      return (
        <Link to={slug} className={classes?.root} {...ice}>
          <img src={mainImage_s} alt={mainImageAlt_s} className="mr-4" />
          <div className="text">
            <h4>{headline_s}</h4>
            <div className="post-meta">
              <span className="mr-2">{formatDate(dateModified)}</span>
            </div>
          </div>
        </Link>
      );
    case IMAGE_BACKGROUND:
      return (
        <Link
          to={slug}
          className={`a-block d-flex align-items-center ${classes?.root ?? ''}`}
          style={{ backgroundImage: `url(${mainImage_s})` }}
        >
          <div className={`text ${classes?.innerWrapper}`} {...ice}>
            <div className="post-meta">
              {
                categories_o &&
                <>
                  {
                    categories_o?.map(category =>
                      <span className="category" key={category.key}>{category.value_smv}</span>
                    )
                  }
                  {' • '}
                </>
              }
              <span className="mr-2">{formatDate(dateModified)}</span>
              {
                numOfComments &&
                <>
                  {' • '}<span className="ml-2"><span className="fa fa-comments"/> {numOfComments}</span>
                </>
              }
            </div>
            <h3>{headline_s}</h3>
            {
              showBlurb && <p>{blurb_t}</p>
            }
          </div>
        </Link>
      );
    default:
      console.error(`Unknown PostCard format "${format}" on post "${headline_s}"`);
      return (
        <Link to={slug} className={classes?.root} {...ice}>
          <h2>{headline_s}</h2>
        </Link>
      );
  }
}
