// sources/react-app/src/shared/DynamicRoute.js
/*
 * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import React, { useEffect, useState } from 'react';

import CircularProgressSpinner from './CircularProgressSpinner';
import { fetchQuery } from '../relayEnvironment';
import byUrlQuery from './queries.graphql';
import { parseDescriptor } from '@craftercms/content';
import { reportNavigation } from '@craftercms/ice';
import { parse } from 'query-string';
import { isAuthoring } from './utils';
import { Guest, ContentType } from '@craftercms/studio-guest';
import contentTypeMap from './contentTypeMap';

const limit = 3;

export default function DynamicRoute(props) {
  const { match, location } = props;
  const [state, setState] = useState(null);
  const url = match.path.includes(':')
    ? match.path.substring(0, match.path.indexOf(':') -1)
    : match.url;

  useEffect(() => {
    let destroyed = false;
    let page = parseInt(parse(location.search).page ?? 1) - 1;
    const pagination = { limit, offset: page ? (page * limit) : 0 };
    reportNavigation(url);
    fetchQuery(
      { text: byUrlQuery },
      {
        url: `.*${url === '/' ? 'website/index' : url}.*`,
        includePosts: true,
        postsLimit: pagination.limit,
        postsOffset: pagination.offset
      }
    ).then(({ data }) => {
      if (!destroyed) {
        const model = parseDescriptor(data.content.items?.[0]);
        const levelDescriptor = data.levelDescriptors.items
          .filter(levelDescriptor => levelDescriptor.file__name === 'crafter-level-descriptor.level.xml')
          .map(levelDescriptor => levelDescriptor)[0];

        setState({
          model,
          meta: {
            siteTitle: levelDescriptor.siteTitle_s,
            socialLinks: levelDescriptor.socialLinks_o.item,
            disqus: {
              websiteShortname: levelDescriptor.websiteShortname_s
            },
            posts: {
              total: data.posts.total,
              ...pagination
            }
          }
        });
        if (model) {
          document.title = model.pageTitle_s ?? 'Wordify Crafter CMS';
          if (model.pageDescription_s) {
            const description = document.head.querySelector('meta[name="description"]');
            description && description.setAttribute('content', model.pageDescription_s ?? '');
          }
        }
      }
    });
    return () => {
      destroyed = true;
    };
  }, [url, location.search]);

  useEffect(() => {
    window.scroll(0, 0);
  }, [url]);

  if (state === null) {
    return <CircularProgressSpinner />;
  } else {
    return (
      <Guest
        modelId={state.model?.craftercms.id}
        isAuthoring={isAuthoring()}
        path={state.model?.craftercms.path}
      >
        <ContentType {...state} {...props} contentTypeMap={contentTypeMap} />
      </Guest>
    );
  }

}

// sources/angular-app/src/app/dynamic-route/dynamic-route.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ContentService } from '../content.service';
import { parseDescriptor } from '@craftercms/content';
import { ContentInstance } from '@craftercms/models';

@Component({
  selector: 'app-dynamic-route',
  templateUrl: './dynamic-route.component.html',
  styleUrls: ['./dynamic-route.component.scss']
})
export class DynamicRouteComponent implements OnInit {
  constructor(private router: Router, private contentService: ContentService, private actRoute: ActivatedRoute) {
    // since router path is `**`, router doesn't load view changes
    // this disables route reuse for the views to load properly
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }
  private url: string = this.getUrlWithoutParams();
  public state;
  public contentTypeId;

  ngOnInit(): void {
    this.contentService.getPageData(this.url, {
      includePosts: true,
      postsLimit: 3,
      postsOffset: 0
    })
      .subscribe(({ data }) => {
        const model = parseDescriptor(data.content.items?.[0]) as ContentInstance;
        const posts = parseDescriptor(data.posts.items);
        const taxonomies = parseDescriptor(data.taxonomies.items);
        const levelDescriptor = data.levelDescriptors.items
          .filter(levelDescriptor => levelDescriptor.file__name === 'crafter-level-descriptor.level.xml')
          .map(levelDescriptor => levelDescriptor)[0];

        this.contentTypeId = model.craftercms.contentTypeId;
        this.state = {
          model,
          posts,
          taxonomies,
          meta: {
            siteTitle: levelDescriptor.siteTitle_s,
            socialLinks: levelDescriptor.socialLinks_o.item,
            disqus: {
              websiteShortname: levelDescriptor.websiteShortname_s
            },
            posts: {
              total: data.posts.total,
              limit: 3,
              offset: 0
            }
          }
        };

        if (model) {
          document.title = model.pageTitle_s ?? 'Wordify Crafter CMS';
          if (model.pageDescription_s) {
            const description = document.head.querySelector('meta[name="description"]');
            description && description.setAttribute('content', model.pageDescription_s ?? '');
          }
        }
      });
  }

  getUrlWithoutParams() {
    let urlTree = this.router.parseUrl(this.router.url);
    urlTree.queryParams = {};
    let routePath = this.actRoute.routeConfig.path;
    const url = routePath.includes(':')
      ? routePath.substring(0, routePath.indexOf(':') -1)
      : urlTree.toString();

    return url;
  }

}

<div [ngSwitch]="contentTypeId">
  <app-home *ngSwitchCase="'/page/entry'" [state]="state"></app-home>
  <app-category *ngSwitchCase="'/page/category'" [state]="state"></app-category>
  <app-contact *ngSwitchCase="'/page/contact'" [state]="state"></app-contact>
  <app-about *ngSwitchCase="'/page/about'" [state]="state"></app-about>
  <app-post *ngSwitchCase="'/component/post'" [state]="state"></app-post>
  <app-search *ngSwitchCase="'/page/search'" [state]="state"></app-search>
  <div *ngSwitchDefault>no view</div>
</div>
