// sources/react-app/src/pages/Post.js
/*
 * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import React, { useState } from 'react';
import BaseLayout from '../shared/BaseLayout';
import ContentType from '../shared/ContentType';
import RecentPostsAside from '../shared/RecentPostsAside';
import PostCard, { IMAGE_BACKGROUND } from '../shared/PostCard';
import { SidebarCategories, SidebarTags } from '../shared/SidebarTaxonomies';
import SidebarSearch from '../shared/SidebarSearch';
import SidebarBios from '../shared/SidebarBios';
import DropZone from '../shared/DropZone';
import Comments, { CommentsCount } from '../shared/Comments';
import { useIntl } from 'react-intl';
import Paginate from '../shared/Paginate';
import { usePosts } from '../shared/hooks';

export default function (props) {
  const {
    model,
    posts,
    meta: {
      siteTitle,
      socialLinks,
      disqus: {
        websiteShortname
      }
    }
  } = props;
  const { formatDate } = useIntl();
  const modelPath = model.craftercms.path;
  const [paginationData, setPaginationData] = useState({
    itemsPerPage: 10,
    currentPage: 0
  });
  const related = usePosts(paginationData, model.categories_o, model.tags_o, model.craftercms.path);

  return (
    <BaseLayout siteTitle={siteTitle} socialLinks={socialLinks}>
      <section className="site-section py-lg">
        <div className="container">
          <div className="row blog-entries element-animate-disabled">

            <div className="col-md-12 col-lg-8 main-content">
              <img src={model.mainImage_s} alt="" className="img-fluid mb-5" />
              <div className="post-meta">
                <span className="author mr-2">
                  <img src={model.authorBio_o[0].profilePic_s} alt="" className="mr-2" /> {model.authorBio_o[0].name_s}
                </span>
                {' • '}<span className="mr-2">{formatDate(model.craftercms.dateCreated)}</span>
                {' • '}<span className="ml-2">
                <span className="fa fa-comments mr-2"/></span>

                <CommentsCount id={model.craftercms.id} websiteShortname={websiteShortname} />
              </div>
              <h1 className="mb-4">{model.headline_s}</h1>
              {
                model.categories_o?.map(category =>
                  <a className="category mb-5" href={`/category/${category.key}`} key={category.key}>{category.value_smv}</a>
                )
              }

              <DropZone
                model={model}
                component="div"
                fieldId="content_o"
                className="post-content-body"
              >
                {
                  model.content_o?.map(component =>
                    <ContentType
                      model={component}
                      key={component.craftercms.id}
                      parentModelId={modelPath}
                    />
                  )
                }
              </DropZone>

              <div className="pt-5">
                <div>
                  Categories:
                  {
                    model.categories_o?.map((category, i) =>
                      <a href={`/category/${category.key}`} key={category.key}>{category.value_smv}{model.categories_o.length === i+1 ? '' : ','}</a>
                    )
                  }
                </div>
                <div>
                  Tags:
                  {
                    model.tags_o?.map((tag, i) =>
                      <a href={`/tag/${tag.key}`} key={tag.key}>#{tag.value_smv}{model.tags_o.length === i+1 ? '' : ','}</a>
                    )
                  }
                </div>
              </div>

              <Comments id={model.craftercms.id} websiteShortname={websiteShortname}/>

            </div>

            <div className="col-md-12 col-lg-4 sidebar">

              <SidebarSearch/>

              <SidebarBios bios={model.authorBio_o}/>

              <RecentPostsAside posts={posts} />

              <SidebarCategories />

              <SidebarTags />

            </div>

          </div>
        </div>
      </section>
      <section className="py-5">
        <div className="container">
          {
            related &&
            <>
              <div className="row">
                <div className="col-md-12">
                  <h2 className="mb-3 ">Related Posts</h2>
                </div>
              </div>
              <div className="row">
                {
                  related?.items.map((post) =>
                    <div key={post.craftercms.id} className="col-md-6 col-lg-4">
                      <PostCard model={post} format={IMAGE_BACKGROUND} classes={{ root: 'sm height-md' }} />
                    </div>
                  )
                }
              </div>
              {
                related?.pageCount > 1 &&
                <nav aria-label="Posts navigation" className="text-center">
                  <Paginate
                    pageCount={related.pageCount}
                    onPageChange={(index) => setPaginationData(
                      {
                        ...paginationData,
                        currentPage: index * paginationData.itemsPerPage
                      })
                    }
                  />
                </nav>
              }
            </>
          }
        </div>
      </section>
    </BaseLayout>
  );
}

// sources/angular-app/src/app/post/post.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ContentService } from '../content.service';
import Utils from '../utils';

@Component({
  selector: 'app-post',
  templateUrl: './post.component.html',
  styleUrls: ['./post.component.scss']
})
export class PostComponent implements OnInit {
  @Input() state;
  public postId;
  public mainImage_s;
  public headline_s;
  public posts_o = [];
  public bios_o;
  public dateCreated;
  public profilePic_s;
  public name_s;
  public path;
  public categories_o = [];
  public tags_o = [];
  public paginationData;
  public content_o;
  public websiteShortname;

  constructor(private contentService: ContentService) {
  }

  getPosts(): void {
    this.contentService.getPosts(
      this.categories_o,
      this.tags_o,
      this.path,
      this.paginationData
    )
      .subscribe(response => {
        this.posts_o = response.items;
        this.paginationData.pageCount = response.pageCount;
      });
  }

  onPageChange(page: number) {
    this.paginationData.currentPage = page;
    this.getPosts();
  }

  ngOnInit(): void {
    this.postId = this.state.model.craftercms.id;
    this.mainImage_s = this.state.model.mainImage_s;
    this.headline_s = this.state.model.headline_s;
    this.dateCreated = Utils.formatDate(this.state.model.craftercms.dateCreated);
    this.bios_o = this.state.model.authorBio_o;
    this.profilePic_s = this.state.model.authorBio_o?.[0]?.profilePic_s;
    this.name_s = this.state.model.authorBio_o?.[0]?.name_s;
    this.path = this.state.model.craftercms.path;
    this.categories_o = this.state.model.categories_o;
    this.tags_o = this.state.model.tags_o;
    this.content_o = this.state.model.content_o;
    this.paginationData = {
      currentPage: 0,
      itemsPerPage: this.state.meta.posts.limit,
      numOfPages: Math.ceil(this.state.meta.posts.total / this.state.meta.posts.limit)
    };

    this.getPosts();

    this.contentService.getLevelDescriptor()
      .subscribe(levelDescriptor => {
        this.websiteShortname = levelDescriptor.websiteShortname_s??'DISQUS';
      })
  }

}

<section class="site-section py-lg">
  <div class="container">
    <div class="row blog-entries element-animate-disabled">

      <div class="col-md-12 col-lg-8 main-content">
        <img class="img-fluid mb-5" src="{{mainImage_s}}">
        <div class="post-meta">
          <span class="author mr-2">
            <img class="mr-2" src={{profilePic_s}} />
            {{name_s}}
          </span>
          • <span class="mr-2">{{dateCreated}}</span>
          • <span class="ml-2">
              <span class="fa fa-comments"></span>
                <app-comments-count *ngIf="websiteShortname" [id]="postId" [websiteShortname]="websiteShortname"></app-comments-count>
              </span>
        </div>
        <h1>{{headline_s}}</h1>
        <a class="category mb-5" *ngFor="let category of categories_o" href="/category/{{category.key}}">
          {{category.value_smv}}
        </a>

        <div class="post-content-body">
          <app-content-type *ngFor="let component of content_o" [model]="component"></app-content-type>
        </div>

        <div class="pt-5">
          <div>
            Categories:
            <a *ngFor="let category of categories_o; let i=index" href="/category/{{category.key}}">
              {{category.value_smv}}{{ i < categories_o.length - 1 ? ',' : '' }}
            </a>
          </div>
          <div>
            Tags:
            <a *ngFor="let tag of tags_o; let i=index" href="/tag/{{tag.key}}">
              #{{tag.value_smv}}{{ i < tags_o.length - 1 ? ',' : '' }}
            </a>
          </div>
        </div>

        <div class="mt-5">
          <app-comments *ngIf="websiteShortname" [id]="postId" [websiteShortname]="websiteShortname"></app-comments>
        </div>
      </div>

      <div class="col-md-12 col-lg-4 sidebar">

        <app-sidebar-search></app-sidebar-search>

        <app-sidebar-bios [bios]="bios_o"></app-sidebar-bios>

        <app-recent-posts-aside></app-recent-posts-aside>

        <app-sidebar-categories></app-sidebar-categories>

        <app-sidebar-tags></app-sidebar-tags>

      </div>

    </div>
  </div>
</section>
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="mb-3">Related Post</h2>
      </div>
    </div>
    <div class="row">
      <div *ngFor="let post of posts_o;" class="col-md-6 col-lg-4">
        <app-post-card
          [classes]="{ root: 'sm height-md' }" [format]="'imageBackground'" [model]="post"
        ></app-post-card>
      </div>
    </div>
    <div *ngIf="paginationData.pageCount > 1" class="row mt-5">
      <div class="col-md-12 text-center">
        <nav aria-label="Page navigation" class="text-center">
          <app-pagination
            [currentPage]="paginationData.currentPage"
            [itemsPerPage]="paginationData.itemsPerPage"
            [pageCount]="paginationData.pageCount"
            [onPageChange]="onPageChange.bind(this)"
          ></app-pagination>
        </nav>
      </div>
    </div>
  </div>
</section>
